export const ReactQueryKeys = {
	server: 'server',
	serverBackups: 'serverBackups',
	serverSettings: 'serverSettings',
	serverFiles: 'serverFiles',
	userServers: 'userServers',
	publicServers: 'publicServers',
	mods: 'mods',
	mod: 'mod',
	modDescription: 'modDescription',
	searchMods: 'searchMods',
	whiteList: 'whiteList',
	operators: 'operators',
	bannedIps: 'bannedIps',
	bannedPlayers: 'bannedPlayers',
}
