import {
	IFileNode,
	IServerCurrentUsageItem,
	IServerProperty,
	ServerPropertyType,
} from '@/shared/types'

export const serverProperties: IServerProperty[] = [
	{
		name: 'max-players',
		value: '20',
		label: 'Кол-во игроков',
		type: ServerPropertyType.Number,
	},
	{
		name: 'gamemode',
		value: 'survival',
		label: 'Режим игры',
		select: {
			options: [
				{ label: 'Выживание', value: 'survival' },
				{ label: 'Творческий', value: 'creative' },
				{ label: 'Приключение', value: 'adventure' },
				{ label: 'Наблюдатель', value: 'spectator' },
			],
		},
		type: ServerPropertyType.Select,
	},
	{
		name: 'difficulty',
		value: 'normal',
		label: 'Сложность',
		select: {
			options: [
				{ label: 'Мирная', value: 'peaceful' },
				{ label: 'Легкая', value: 'easy' },
				{ label: 'Нормальная', value: 'normal' },
				{ label: 'Тяжелая', value: 'hard' },
			],
		},
		type: ServerPropertyType.Select,
	},
	{
		name: 'white-list',
		value: 'false',
		label: 'Белый список',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'online-mode',
		value: 'false',
		label: 'Пиратский',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'pvp',
		value: 'true',
		label: 'PvP',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'enable-command-block',
		value: 'true',
		label: 'Командные блоки',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'allow-flight',
		value: 'true',
		label: 'Полёт',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'spawn-animals',
		value: 'true',
		label: 'Животные',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'spawn-monsters',
		value: 'true',
		label: 'Монстры',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'spawn-npcs',
		value: 'true',
		label: 'Деревенские жители',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'allow-nether',
		value: 'true',
		label: 'Адский мир',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'generate-structures',
		value: 'true',
		label: 'Генерировать структуры',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'force-gamemode',
		value: 'false',
		label: 'Сбрасывать режим игры',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'spawn-protect',
		value: '0',
		label: 'Защита спавна',
		type: ServerPropertyType.Number,
	},
	{
		name: 'require-resource-pack',
		value: 'false',
		label: 'Требовать ресурс-пак',
		type: ServerPropertyType.Boolean,
	},
	{
		name: 'view-distance',
		value: '5',
		label: 'Дальность прорисовки',
		type: ServerPropertyType.Number,
	},
	{
		name: 'simulation-distance',
		value: '5',
		label: 'Дальность симуляции',
		type: ServerPropertyType.Number,
	},
	{
		name: 'max-build-height',
		value: '256',
		label: 'Макс. высота строительства',
		type: ServerPropertyType.Number,
	},
	{
		name: 'level-name',
		value: 'world',
		label: 'Название мира',
		type: ServerPropertyType.String,
	},
	{
		name: 'level-seed',
		value: '',
		label: 'Ключ генерации',
		type: ServerPropertyType.String,
	},
	{
		name: 'hardcore',
		value: 'false',
		label: 'Хардкор',
		type: ServerPropertyType.Boolean,
	},
]

export const serverCurrentUsage: IServerCurrentUsageItem[] = [
	{ label: 'Процессор', value: 72, maxValue: 100, color: 'purple', isPercent: true },
	{ label: 'Опер. память', value: 1780, maxValue: 2500, color: 'blue', valueUnit: 'MB' },
	{ label: 'хранилище', value: 0.9, maxValue: 5, color: 'orange', valueUnit: 'GB' },
]

export const filesTree: IFileNode[] = [
	{
		path: 'banned-ips.json',
		name: 'banned-ips.json',
		type: 'file',
		extension: '.json',
		size: 2,
	},
	{
		path: 'banned-players.json',
		name: 'banned-players.json',
		type: 'file',
		extension: '.json',
		size: 2,
	},
	{
		path: 'eula.txt',
		name: 'eula.txt',
		type: 'file',
		extension: '.txt',
		size: 160,
	},
	{
		path: 'ops.json',
		name: 'ops.json',
		type: 'file',
		extension: '.json',
		size: 138,
	},
	{
		path: 'server.properties',
		name: 'server.properties',
		type: 'file',
		extension: '.properties',
		size: 1344,
	},
	{
		path: 'usercache.json',
		name: 'usercache.json',
		type: 'file',
		extension: '.json',
		size: 109,
	},
	{
		path: 'whitelist.json',
		name: 'whitelist.json',
		type: 'file',
		extension: '.json',
		size: 2,
	},
	{ path: 'world', name: 'world', type: 'directory', size: 22734954 },
	{ path: 'world/advancements', name: 'advancements', type: 'directory', size: 1622 },
	{
		path: 'world/advancements/ab7f5963-f01d-3980-8fa8-a422e88f9d12.json',
		name: 'ab7f5963-f01d-3980-8fa8-a422e88f9d12.json',
		type: 'file',
		extension: '.json',
		size: 1622,
	},
	{ path: 'world/data', name: 'data', type: 'directory', size: 90 },
	{
		path: 'world/data/raids.dat',
		name: 'raids.dat',
		type: 'file',
		extension: '.dat',
		size: 90,
	},
	{
		path: 'world/datapacks',
		name: 'datapacks',
		type: 'directory',
		size: 0,
	},
	{
		path: 'world/DIM-1',
		name: 'DIM-1',
		type: 'directory',
		size: 90,
	},
	{
		path: 'world/DIM-1/data',
		name: 'data',
		type: 'directory',
		size: 90,
	},
	{
		path: 'world/DIM-1/data/raids.dat',
		name: 'raids.dat',
		type: 'file',
		extension: '.dat',
		size: 90,
	},
	{
		path: 'world/DIM-1/data/boda.dat',
		name: 'boda.dat',
		type: 'file',
		extension: '.dat',
		size: 90,
	},
	{
		path: 'world/entities',
		name: 'entities',
		type: 'directory',
		size: 868352,
	},
	{
		path: 'world/entities/r.-1.-1.mca',
		name: 'r.-1.-1.mca',
		type: 'file',
		extension: '.mca',
		size: 102400,
	},
	{
		path: 'world/entities/r.-1.0.mca',
		name: 'r.-1.0.mca',
		type: 'file',
		extension: '.mca',
		size: 544768,
	},
	{
		path: 'world/entities/r.-2.0.mca',
		name: 'r.-2.0.mca',
		type: 'file',
		extension: '.mca',
		size: 36864,
	},
	{
		path: 'world/entities/r.0.-1.mca',
		name: 'r.0.-1.mca',
		type: 'file',
		extension: '.mca',
		size: 98304,
	},
	{
		path: 'world/entities/r.0.0.mca',
		name: 'r.0.0.mca',
		type: 'file',
		extension: '.mca',
		size: 86016,
	},
	{
		path: 'world/level.dat',
		name: 'level.dat',
		type: 'file',
		extension: '.dat',
		size: 1401,
	},
	{
		path: 'world/level.dat_old',
		name: 'level.dat_old',
		type: 'file',
		extension: '.dat_old',
		size: 1405,
	},
	{
		path: 'world/playerdata',
		name: 'playerdata',
		type: 'directory',
		size: 1014,
	},
	{
		path: 'world/playerdata/ab7f5963-f01d-3980-8fa8-a422e88f9d12.dat',
		name: 'ab7f5963-f01d-3980-8fa8-a422e88f9d12.dat',
		type: 'file',
		extension: '.dat',
		size: 1014,
	},
	{
		path: 'world/poi',
		name: 'poi',
		type: 'directory',
		size: 0,
	},
	{
		path: 'world/poi/r.-1.-1.mca',
		name: 'r.-1.-1.mca',
		type: 'file',
		extension: '.mca',
		size: 0,
	},
	{
		path: 'world/poi/r.-1.0.mca',
		name: 'r.-1.0.mca',
		type: 'file',
		extension: '.mca',
		size: 0,
	},
	{
		path: 'world/poi/r.0.-1.mca',
		name: 'r.0.-1.mca',
		type: 'file',
		extension: '.mca',
		size: 0,
	},
	{
		path: 'world/poi/r.0.0.mca',
		name: 'r.0.0.mca',
		type: 'file',
		extension: '.mca',
		size: 0,
	},
	{
		path: 'world/region',
		name: 'region',
		type: 'directory',
		size: 21860352,
	},
	{
		path: 'world/region/r.-1.-1.mca',
		name: 'r.-1.-1.mca',
		type: 'file',
		extension: '.mca',
		size: 4947968,
	},
	{
		path: 'world/region/r.-1.0.mca',
		name: 'r.-1.0.mca',
		type: 'file',
		extension: '.mca',
		size: 7278592,
	},
	{
		path: 'world/region/r.-1.1.mca',
		name: 'r.-1.1.mca',
		type: 'file',
		extension: '.mca',
		size: 135168,
	},
	{
		path: 'world/region/r.-2.-1.mca',
		name: 'r.-2.-1.mca',
		type: 'file',
		extension: '.mca',
		size: 909312,
	},
	{
		path: 'world/region/r.-2.0.mca',
		name: 'r.-2.0.mca',
		type: 'file',
		extension: '.mca',
		size: 2314240,
	},
	{
		path: 'world/region/r.-2.1.mca',
		name: 'r.-2.1.mca',
		type: 'file',
		extension: '.mca',
		size: 65536,
	},
	{
		path: 'world/region/r.0.-1.mca',
		name: 'r.0.-1.mca',
		type: 'file',
		extension: '.mca',
		size: 3022848,
	},
	{
		path: 'world/region/r.0.0.mca',
		name: 'r.0.0.mca',
		type: 'file',
		extension: '.mca',
		size: 3186688,
	},
	{
		path: 'world/session.lock',
		name: 'session.lock',
		type: 'file',
		extension: '.lock',
		size: 3,
	},
	{
		path: 'world/stats',
		name: 'stats',
		type: 'directory',
		size: 535,
	},
	{
		path: 'world/stats/ab7f5963-f01d-3980-8fa8-a422e88f9d12.json',
		name: 'ab7f5963-f01d-3980-8fa8-a422e88f9d12.json',
		type: 'file',
		extension: '.json',
		size: 535,
	},
	{ path: 'libraries', name: 'libraries', type: 'directory', size: 251512 },
	{
		path: 'libraries/com',
		name: 'com',
		type: 'directory',
		size: 5098995,
	},
	{
		path: 'libraries/com/github',
		name: 'github',
		type: 'directory',
		size: 947865,
	},
	{
		path: 'libraries/com/github/oshi',
		name: 'oshi',
		type: 'directory',
		size: 947865,
	},
	{
		path: 'libraries/com/github/oshi/oshi-core',
		name: 'oshi-core',
		type: 'directory',
		size: 947865,
	},
	{
		path: 'libraries/com/github/oshi/oshi-core/6.2.2',
		name: '6.2.2',
		type: 'directory',
		size: 947865,
	},
	{
		path: 'libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar',
		name: 'oshi-core-6.2.2.jar',
		type: 'file',
		extension: '.jar',
		size: 947865,
	},
	{
		path: 'libraries/com/google',
		name: 'google',
		type: 'directory',
		size: 3250331,
	},
	{
		path: 'libraries/com/google/code',
		name: 'code',
		type: 'directory',
		size: 286235,
	},
	{
		path: 'libraries/com/google/code/gson',
		name: 'gson',
		type: 'directory',
		size: 286235,
	},
	{
		path: 'libraries/com/google/code/gson/gson',
		name: 'gson',
		type: 'directory',
		size: 286235,
	},
	{
		path: 'libraries/com/google/code/gson/gson/2.10',
		name: '2.10',
		type: 'directory',
		size: 286235,
	},
	{
		path: 'libraries/com/google/code/gson/gson/2.10/gson-2.10.jar',
		name: 'gson-2.10.jar',
		type: 'file',
		extension: '.jar',
		size: 286235,
	},
	{
		path: 'libraries/com/google/guava',
		name: 'guava',
		type: 'directory',
		size: 2964096,
	},
	{
		path: 'libraries/com/google/guava/failureaccess',
		name: 'failureaccess',
		type: 'directory',
		size: 4617,
	},
	{
		path: 'libraries/com/google/guava/failureaccess/1.0.1',
		name: '1.0.1',
		type: 'directory',
		size: 4617,
	},
	{
		path: 'libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar',
		name: 'failureaccess-1.0.1.jar',
		type: 'file',
		extension: '.jar',
		size: 4617,
	},
	{
		path: 'libraries/com/google/guava/guava',
		name: 'guava',
		type: 'directory',
		size: 2959479,
	},
	{
		path: 'libraries/com/google/guava/guava/31.1-jre',
		name: '31.1-jre',
		type: 'directory',
		size: 2959479,
	},
	{
		path: 'libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar',
		name: 'guava-31.1-jre.jar',
		type: 'file',
		extension: '.jar',
		size: 2959479,
	},
	// {
	// 	path: 'libraries/com/mojang',
	// 	name: 'mojang',
	// 	children: [
	// 		{
	// 			path: 'libraries/com/mojang/authlib',
	// 			name: 'authlib',
	// 			children: [
	// 				{
	// 					path: 'libraries/com/mojang/authlib/3.18.38',
	// 					name: '3.18.38',
	// 					children: [
	// 						{
	// 							path: 'libraries/com/mojang/authlib/3.18.38/authlib-3.18.38.jar',
	// 							name: 'authlib-3.18.38.jar',
	// 							type: 'file',
	// 							extension: '.jar',
	// 							size: 118354,
	// 						},
	// 					],
	// 					type: 'directory',
	// 					size: 118354,
	// 				},
	// 			],
	// 			type: 'directory',
	// 			size: 118354,
	// 		},
	// 		{
	// 			path: 'libraries/com/mojang/brigadier',
	// 			name: 'brigadier',
	// 			children: [
	// 				{
	// 					path: 'libraries/com/mojang/brigadier/1.0.18',
	// 					name: '1.0.18',
	// 					children: [
	// 						{
	// 							path: 'libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar',
	// 							name: 'brigadier-1.0.18.jar',
	// 							type: 'file',
	// 							extension: '.jar',
	// 							size: 77116,
	// 						},
	// 					],
	// 					type: 'directory',
	// 					size: 77116,
	// 				},
	// 			],
	// 			type: 'directory',
	// 			size: 77116,
	// 		},
	// 		{
	// 			path: 'libraries/com/mojang/datafixerupper',
	// 			name: 'datafixerupper',
	// 			children: [
	// 				{
	// 					path: 'libraries/com/mojang/datafixerupper/6.0.6',
	// 					name: '6.0.6',
	// 					children: [
	// 						{
	// 							path: 'libraries/com/mojang/datafixerupper/6.0.6/datafixerupper-6.0.6.jar',
	// 							name: 'datafixerupper-6.0.6.jar',
	// 							type: 'file',
	// 							extension: '.jar',
	// 							size: 689986,
	// 						},
	// 					],
	// 					type: 'directory',
	// 					size: 689986,
	// 				},
	// 			],
	// 			type: 'directory',
	// 			size: 689986,
	// 		},
	// 		{
	// 			path: 'libraries/com/mojang/logging',
	// 			name: 'logging',
	// 			children: [
	// 				{
	// 					path: 'libraries/com/mojang/logging/1.1.1',
	// 					name: '1.1.1',
	// 					children: [
	// 						{
	// 							path: 'libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar',
	// 							name: 'logging-1.1.1.jar',
	// 							type: 'file',
	// 							extension: '.jar',
	// 							size: 15343,
	// 						},
	// 					],
	// 					type: 'directory',
	// 					size: 15343,
	// 				},
	// 			],
	// 			type: 'directory',
	// 			size: 15343,
	// 		},
	// 	],
	// 	type: 'directory',
	// 	size: 900799,
	// },
]
