import { IGameTariffs, ITariff } from '@/shared/types/tariff.types'

export const groupedTariffs: IGameTariffs[] = [
	{
		gameId: 1,
		gameName: 'Fortnite',
		gameIconUrl: 'https://example.com/fortnite.png',
		gameDescription: 'Fortnite is a popular battle royale game developed by Epic Games.',
		tariffs: [
			{
				id: 1,
				gameId: 1,
				name: 'Standard',
				description: 'Enjoy the standard gaming experience with this Fortnite tariff.',
				minSlots: 2,
				maxSlots: 10,
				monthPrice: 200,
				isPricePerPlayer: false,
				allocatedCpu: 40,
				allocatedDiskSpace: 15360,
				allocatedMemory: 8192,
				cpuFrequency: 3500,
				cpuName: 'Intel Core i7',
				isCpuPerSlot: false,
				isMemoryPerSlot: false,
				locations: [
					{
						id: 1,
						name: 'North America',
						testIp: '192.168.0.1',
					},
					{
						id: 2,
						name: 'Europe',
						testIp: '192.168.0.2',
					},
				],
			},
			{
				id: 2,
				gameId: 1,
				name: 'Premium',
				description: 'Upgrade to the premium tariff for enhanced features and performance.',
				minSlots: 5,
				maxSlots: 20,
				monthPrice: 400,
				isPricePerPlayer: false,
				allocatedCpu: 100,
				allocatedDiskSpace: 30720,
				allocatedMemory: 16384,
				cpuFrequency: 4000,
				cpuName: 'Intel Core i9',
				isCpuPerSlot: true,
				isMemoryPerSlot: true,
				locations: [
					{
						id: 1,
						name: 'North America',
						testIp: '192.168.0.1',
					},
					{
						id: 3,
						name: 'Asia',
						testIp: '192.168.0.3',
					},
				],
			},
		],
	},
	{
		gameId: 2,
		gameName: 'Minecraft',
		gameIconUrl: 'https://example.com/minecraft.png',
		gameDescription:
			'Minecraft is a sandbox game that allows players to build and explore virtual worlds.',
		tariffs: [
			{
				id: 3,
				gameId: 2,
				name: 'Basic',
				description: 'Experience the basics of Minecraft with this tariff.',
				minSlots: 4,
				maxSlots: 8,
				monthPrice: 15,
				isPricePerPlayer: true,
				allocatedCpu: 60,
				allocatedDiskSpace: 15360,
				allocatedMemory: 12288,
				cpuFrequency: 3800,
				cpuName: 'AMD Ryzen 5',
				isCpuPerSlot: false,
				isMemoryPerSlot: false,
				locations: [
					{
						id: 1,
						name: 'North America',
						testIp: '192.168.0.1',
					},
					{
						id: 4,
						name: 'South America',
						testIp: '192.168.0.4',
					},
				],
			},
			{
				id: 4,
				gameId: 2,
				name: 'Advanced',
				description: 'Unleash your creativity with the advanced features of Minecraft.',
				minSlots: 10,
				maxSlots: 30,
				monthPrice: 30,
				isPricePerPlayer: true,
				allocatedCpu: 120,
				allocatedDiskSpace: 30720,
				allocatedMemory: 24576,
				cpuFrequency: 4700,
				cpuName: 'AMD Ryzen 7',
				isCpuPerSlot: true,
				isMemoryPerSlot: true,
				locations: [
					{
						id: 1,
						name: 'North America',
						testIp: '192.168.0.1',
					},
					{
						id: 5,
						name: 'Oceania',
						testIp: '192.168.0.5',
					},
				],
			},
		],
	},
	{
		gameId: 3,
		gameName: 'League of Legends',
		gameIconUrl: 'https://example.com/leagueoflegends.png',
		gameDescription: 'League of Legends is a popular multiplayer online battle arena (MOBA) game.',
		tariffs: [
			{
				id: 5,
				gameId: 3,
				name: 'Starter',
				description: 'Get started with League of Legends with this beginner-friendly tariff.',
				minSlots: 1,
				maxSlots: 5,
				monthPrice: 10,
				isPricePerPlayer: true,
				allocatedCpu: 50,
				allocatedDiskSpace: 15360,
				allocatedMemory: 4096,
				cpuFrequency: 3100,
				cpuName: 'Intel Core i3',
				isCpuPerSlot: false,
				isMemoryPerSlot: false,
				locations: [
					{
						id: 1,
						name: 'North America',
						testIp: '192.168.0.1',
					},
					{
						id: 6,
						name: 'Africa',
						testIp: '192.168.0.6',
					},
				],
			},
			{
				id: 6,
				gameId: 3,
				name: 'Pro',
				description:
					'Take your League of Legends skills to the professional level with this tariff.',
				minSlots: 3,
				maxSlots: 15,
				monthPrice: 20,
				isPricePerPlayer: true,
				allocatedCpu: 100,
				allocatedDiskSpace: 30720,
				allocatedMemory: 8192,
				cpuFrequency: 4300,
				cpuName: 'Intel Core i7',
				isCpuPerSlot: true,
				isMemoryPerSlot: true,
				locations: [
					{
						id: 1,
						name: 'North America',
						testIp: '192.168.0.1',
					},
					{
						id: 7,
						name: 'Europe',
						testIp: '192.168.0.7',
					},
				],
			},
		],
	},
	{
		gameId: 4,
		gameName: 'Call of Duty: Warzone',
		gameIconUrl: 'https://example.com/warzone.png',
		gameDescription: 'Call of Duty: Warzone is a popular free-to-play battle royale game.',
		tariffs: [
			{
				id: 7,
				gameId: 4,
				name: 'Standard',
				description:
					'Experience the intense action of Call of Duty: Warzone with this standard tariff.',
				minSlots: 2,
				maxSlots: 6,
				monthPrice: 200,
				isPricePerPlayer: false,
				allocatedCpu: 70,
				allocatedDiskSpace: 30720,
				allocatedMemory: 4096,
				cpuFrequency: 2900,
				cpuName: 'Intel Core i3',
				isCpuPerSlot: false,
				isMemoryPerSlot: false,
				locations: [
					{
						id: 1,
						name: 'North America',
						testIp: '192.168.0.1',
					},
					{
						id: 8,
						name: 'Asia',
						testIp: '192.168.0.8',
					},
				],
			},
			{
				id: 8,
				gameId: 4,
				name: 'Premium',
				description:
					'Advanced tariff, you can play with all your friends with maximum performance. No lags. 100%.',
				minSlots: 2,
				maxSlots: 6,
				monthPrice: 400,
				isPricePerPlayer: false,
				allocatedCpu: 140,
				allocatedDiskSpace: 51200,
				allocatedMemory: 4096,
				cpuFrequency: 4800,
				cpuName: 'Intel Core i3',
				isCpuPerSlot: false,
				isMemoryPerSlot: false,
				locations: [
					{
						id: 1,
						name: 'North America',
						testIp: '192.168.0.1',
					},
					{
						id: 8,
						name: 'Asia',
						testIp: '192.168.0.8',
					},
				],
			},
		],
	},
]

export const tariffs: ITariff[] = [
	{
		id: 1,
		gameId: 1,
		name: 'Standard',
		description: 'Enjoy the standard gaming experience with this Fortnite tariff.',
		minSlots: 2,
		maxSlots: 10,
		monthPrice: 9.99,
		isPricePerPlayer: false,
		allocatedCpu: 4,
		allocatedDiskSpace: 100,
		allocatedMemory: 8192,
		cpuFrequency: 3500,
		cpuName: 'Intel Core i7',
		isCpuPerSlot: false,
		isMemoryPerSlot: false,
		locations: [
			{
				id: 1,
				name: 'North America',
				testIp: '192.168.0.1',
			},
			{
				id: 2,
				name: 'Europe',
				testIp: '192.168.0.2',
			},
		],
	},
	{
		id: 2,
		gameId: 1,
		name: 'Premium',
		description: 'Upgrade to the premium tariff for enhanced features and performance.',
		minSlots: 5,
		maxSlots: 20,
		monthPrice: 19.99,
		isPricePerPlayer: true,
		allocatedCpu: 8,
		allocatedDiskSpace: 200,
		allocatedMemory: 16384,
		cpuFrequency: 4000,
		cpuName: 'Intel Core i9',
		isCpuPerSlot: true,
		isMemoryPerSlot: true,
		locations: [
			{
				id: 1,
				name: 'North America',
				testIp: '192.168.0.1',
			},
			{
				id: 3,
				name: 'Asia',
				testIp: '192.168.0.3',
			},
		],
	},
	{
		id: 3,
		gameId: 2,
		name: 'Basic',
		description: 'Experience the basics of Minecraft with this tariff.',
		minSlots: 4,
		maxSlots: 8,
		monthPrice: 14.99,
		isPricePerPlayer: false,
		allocatedCpu: 6,
		allocatedDiskSpace: 150,
		allocatedMemory: 12288,
		cpuFrequency: 3800,
		cpuName: 'AMD Ryzen 5',
		isCpuPerSlot: false,
		isMemoryPerSlot: false,
		locations: [
			{
				id: 1,
				name: 'North America',
				testIp: '192.168.0.1',
			},
			{
				id: 4,
				name: 'South America',
				testIp: '192.168.0.4',
			},
		],
	},
	{
		id: 4,
		gameId: 2,
		name: 'Advanced',
		description: 'Unleash your creativity with the advanced features of Minecraft.',
		minSlots: 10,
		maxSlots: 30,
		monthPrice: 29.99,
		isPricePerPlayer: true,
		allocatedCpu: 12,
		allocatedDiskSpace: 300,
		allocatedMemory: 24576,
		cpuFrequency: 4200,
		cpuName: 'AMD Ryzen 7',
		isCpuPerSlot: true,
		isMemoryPerSlot: true,
		locations: [
			{
				id: 1,
				name: 'North America',
				testIp: '192.168.0.1',
			},
			{
				id: 5,
				name: 'Oceania',
				testIp: '192.168.0.5',
			},
		],
	},
	{
		id: 5,
		gameId: 3,
		name: 'Starter',
		description: 'Get started with League of Legends with this beginner-friendly tariff.',
		minSlots: 1,
		maxSlots: 5,
		monthPrice: 4.99,
		isPricePerPlayer: false,
		allocatedCpu: 2,
		allocatedDiskSpace: 50,
		allocatedMemory: 4096,
		cpuFrequency: 5400,
		cpuName: 'Intel Core i3',
		isCpuPerSlot: false,
		isMemoryPerSlot: false,
		locations: [
			{
				id: 1,
				name: 'North America',
				testIp: '192.168.0.1',
			},
			{
				id: 6,
				name: 'Africa',
				testIp: '192.168.0.6',
			},
		],
	},
	{
		id: 6,
		gameId: 3,
		name: 'Pro',
		description: 'Take your League of Legends skills to the professional level with this tariff.',
		minSlots: 3,
		maxSlots: 15,
		monthPrice: 9.99,
		isPricePerPlayer: true,
		allocatedCpu: 4,
		allocatedDiskSpace: 100,
		allocatedMemory: 8192,
		cpuFrequency: 3.5,
		cpuName: 'Intel Core i7',
		isCpuPerSlot: true,
		isMemoryPerSlot: true,
		locations: [
			{
				id: 1,
				name: 'North America',
				testIp: '192.168.0.1',
			},
			{
				id: 7,
				name: 'Europe',
				testIp: '192.168.0.7',
			},
		],
	},
	{
		id: 7,
		gameId: 4,
		name: 'Standard',
		description:
			'Experience the intense action of Call of Duty: Warzone with this standard tariff.',
		minSlots: 2,
		maxSlots: 6,
		monthPrice: 9.99,
		isPricePerPlayer: false,
		allocatedCpu: 2,
		allocatedDiskSpace: 50,
		allocatedMemory: 4096,
		cpuFrequency: 2.2,
		cpuName: 'Intel Core i3',
		isCpuPerSlot: false,
		isMemoryPerSlot: false,
		locations: [
			{
				id: 1,
				name: 'North America',
				testIp: '192.168.0.1',
			},
			{
				id: 8,
				name: 'Asia',
				testIp: '192.168.0.8',
			},
		],
	},
	{
		id: 8,
		gameId: 4,
		name: 'Premium',
		description:
			'Advanced tariff, you can play with all your friends with maximum performance. No lags. 100%.',
		minSlots: 2,
		maxSlots: 6,
		monthPrice: 9.99,
		isPricePerPlayer: false,
		allocatedCpu: 2,
		allocatedDiskSpace: 50,
		allocatedMemory: 4096,
		cpuFrequency: 2.2,
		cpuName: 'Intel Core i3',
		isCpuPerSlot: false,
		isMemoryPerSlot: false,
		locations: [
			{
				id: 1,
				name: 'North America',
				testIp: '192.168.0.1',
			},
			{
				id: 8,
				name: 'Asia',
				testIp: '192.168.0.8',
			},
		],
	},
]
