import { IGameTariffs } from '@/shared/types/tariff.types'

export const groupedTariffs: IGameTariffs[] = [
	{
		gameId: 0,
		gameName: 'Minecraft',
		gameImageUrl: 'https://hypixel.net/attachments/image_2022-01-19_205222-png.2875248/',
		gameDescription: 'Minecraft',
		tariffs: [
			{
				id: 0,
				gameId: 0,
				name: 'Vanila / Plugins',
				description:
					'Тариф для игры без модов, на облегченном ядре, с небольшим кол-вом плагонов\nидеально подойдет для небольшого дружеского сервера.',
				minSlots: 0,
				maxSlots: 100,
				monthPrice: 20,
				isPricePerPlayer: true,
				allocatedCpu: 100,
				allocatedDiskSpace: 16384,
				allocatedMemory: 16384,
				cpuFrequency: 3000,
				cpuName: 'default',
				isMemoryPerSlot: false,
				isCpuPerSlot: false,
				locations: [
					{
						id: 0,
						name: 'Default',
						description: 'Yandex default host',
						testIp: '127.0.0.1',
					},
				],
			},
			{
				id: 1,
				gameId: 0,
				name: 'Vanila / Improved',
				description: 'Тариф для игры с модами или большим количеством игроков',
				minSlots: 0,
				maxSlots: 100,
				monthPrice: 50,
				isPricePerPlayer: false,
				allocatedCpu: 20,
				allocatedDiskSpace: 8192,
				allocatedMemory: 4096,
				cpuFrequency: 3000,
				cpuName: 'default',
				isMemoryPerSlot: false,
				isCpuPerSlot: false,
				locations: [
					{
						id: 0,
						name: 'Default',
						description: 'Yandex default host',
						testIp: '127.0.0.1',
					},
				],
			},
		],
	},
	{
		gameId: 1,
		gameName: 'CS 1.6',
		gameImageUrl:
			'https://files.softicons.com/download/game-icons/league-of-legends-icons-by-fazie69/png/512x512/Lissandra%20Bloodstone.png',
		gameDescription: 'CS 1.6',
		tariffs: [
			{
				id: 2,
				gameId: 1,
				name: 'Classic / Low',
				description: 'Тариф для небольшого количества игроков',
				minSlots: 0,
				maxSlots: 100,
				monthPrice: 50,
				isPricePerPlayer: false,
				allocatedCpu: 20,
				allocatedDiskSpace: 8192,
				allocatedMemory: 2048,
				cpuFrequency: 3000,
				cpuName: 'default',
				isMemoryPerSlot: false,
				isCpuPerSlot: false,
				locations: [
					{
						id: 0,
						name: 'Default',
						description: 'Yandex default host',
						testIp: '127.0.0.1',
					},
				],
			},
			{
				id: 3,
				gameId: 1,
				name: 'Classic / Standard',
				description: 'Тариф для большого количетва игроков',
				minSlots: 0,
				maxSlots: 100,
				monthPrice: 100,
				isPricePerPlayer: false,
				allocatedCpu: 50,
				allocatedDiskSpace: 8192,
				allocatedMemory: 4096,
				cpuFrequency: 3000,
				cpuName: 'default',
				isMemoryPerSlot: false,
				isCpuPerSlot: false,
				locations: [
					{
						id: 0,
						name: 'Default',
						description: 'Yandex default host',
						testIp: '127.0.0.1',
					},
				],
			},
		],
	},
	{
		gameId: 2,
		gameName: "Garry's Mod",
		gameImageUrl: 'https://mobimg.b-cdn.net/v2/fetch/e1/e1b6bcab086182254acc1733c0e27281.png',
		gameDescription: "Garry's mod",
		tariffs: [
			{
				id: 4,
				gameId: 2,
				name: 'Classic / Low',
				description: 'Описание тарифа',
				minSlots: 0,
				maxSlots: 100,
				monthPrice: 50,
				isPricePerPlayer: false,
				allocatedCpu: 20,
				allocatedDiskSpace: 8192,
				allocatedMemory: 2048,
				cpuFrequency: 3000,
				cpuName: 'default',
				isMemoryPerSlot: false,
				isCpuPerSlot: false,
				locations: [
					{
						id: 0,
						name: 'Default',
						description: 'Yandex default host',
						testIp: '127.0.0.1',
					},
				],
			},
			{
				id: 5,
				gameId: 2,
				name: 'Classic / Standard',
				description: 'Описание тарифа',
				minSlots: 0,
				maxSlots: 100,
				monthPrice: 100,
				isPricePerPlayer: false,
				allocatedCpu: 50,
				allocatedDiskSpace: 8192,
				allocatedMemory: 4096,
				cpuFrequency: 3000,
				cpuName: 'default',
				isMemoryPerSlot: false,
				isCpuPerSlot: false,
				locations: [
					{
						id: 0,
						name: 'Default',
						description: 'Yandex default host',
						testIp: '127.0.0.1',
					},
				],
			},
		],
	},
]

// export const groupedTariffs: IGameTariffs[] = [
// 	{
// 		gameId: 1,
// 		gameName: 'Fortnite',
// 		gameImageUrl: 'https://mobimg.b-cdn.net/v2/fetch/e1/e1b6bcab086182254acc1733c0e27281.png',
// 		gameDescription: 'Fortnite is a popular battle royale game developed by Epic Games.',
// 		tariffs: [
// 			{
// 				id: 1,
// 				gameId: 1,
// 				name: 'Standard',
// 				description: 'Enjoy the standard gaming experience with this Fortnite tariff.',
// 				minSlots: 2,
// 				maxSlots: 10,
// 				monthPrice: 30,
// 				isPricePerPlayer: true,
// 				allocatedCpu: 40,
// 				allocatedDiskSpace: 15360,
// 				allocatedMemory: 8192,
// 				cpuFrequency: 3500,
// 				cpuName: 'Intel Core i7',
// 				isCpuPerSlot: false,
// 				isMemoryPerSlot: false,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 2,
// 						name: 'Europe',
// 						description: 'Europe',
// 						testIp: '192.168.0.2',
// 					},
// 				],
// 			},
// 			{
// 				id: 2,
// 				gameId: 1,
// 				name: 'Premium',
// 				description: 'Upgrade to the premium tariff for enhanced features and performance.',
// 				minSlots: 5,
// 				maxSlots: 20,
// 				monthPrice: 400,
// 				isPricePerPlayer: false,
// 				allocatedCpu: 100,
// 				allocatedDiskSpace: 30720,
// 				allocatedMemory: 16384,
// 				cpuFrequency: 4000,
// 				cpuName: 'Intel Core i9',
// 				isCpuPerSlot: true,
// 				isMemoryPerSlot: true,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 3,
// 						name: 'Asia',
// 						description: 'Asia',
// 						testIp: '192.168.0.3',
// 					},
// 				],
// 			},
// 			{
// 				id: 9,
// 				gameId: 1,
// 				name: 'Premium Test',
// 				description: 'Upgrade to the premium tariff for enhanced features and performance. Test',
// 				minSlots: 5,
// 				maxSlots: 20,
// 				monthPrice: 400,
// 				isPricePerPlayer: false,
// 				allocatedCpu: 100,
// 				allocatedDiskSpace: 30720,
// 				allocatedMemory: 16384,
// 				cpuFrequency: 4000,
// 				cpuName: 'Intel Core i9',
// 				isCpuPerSlot: true,
// 				isMemoryPerSlot: true,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 3,
// 						name: 'Asia',
// 						description: 'Asia',
// 						testIp: '192.168.0.3',
// 					},
// 				],
// 			},
// 		],
// 	},
// 	{
// 		gameId: 2,
// 		gameName: 'Minecraft',
// 		gameImageUrl: 'https://hypixel.net/attachments/image_2022-01-19_205222-png.2875248/',
// 		gameDescription:
// 			'Minecraft is a sandbox game that allows players to build and explore virtual worlds.',
// 		tariffs: [
// 			{
// 				id: 3,
// 				gameId: 2,
// 				name: 'Basic',
// 				description: 'Experience the basics of Minecraft with this tariff.',
// 				minSlots: 4,
// 				maxSlots: 8,
// 				monthPrice: 15,
// 				isPricePerPlayer: true,
// 				allocatedCpu: 60,
// 				allocatedDiskSpace: 15360,
// 				allocatedMemory: 12288,
// 				cpuFrequency: 3800,
// 				cpuName: 'AMD Ryzen 5',
// 				isCpuPerSlot: false,
// 				isMemoryPerSlot: false,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 4,
// 						name: 'South America',
// 						description: 'South America',
// 						testIp: '192.168.0.4',
// 					},
// 				],
// 			},
// 			{
// 				id: 4,
// 				gameId: 2,
// 				name: 'Advanced',
// 				description: 'Unleash your creativity with the advanced features of Minecraft.',
// 				minSlots: 10,
// 				maxSlots: 30,
// 				monthPrice: 30,
// 				isPricePerPlayer: true,
// 				allocatedCpu: 120,
// 				allocatedDiskSpace: 30720,
// 				allocatedMemory: 24576,
// 				cpuFrequency: 4700,
// 				cpuName: 'AMD Ryzen 7',
// 				isCpuPerSlot: true,
// 				isMemoryPerSlot: true,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 5,
// 						name: 'Oceania',
// 						description: 'Oceania',
// 						testIp: '192.168.0.5',
// 					},
// 				],
// 			},
// 		],
// 	},
// 	{
// 		gameId: 3,
// 		gameName: 'League of Legends',
// 		gameImageUrl:
// 			'https://files.softicons.com/download/game-icons/league-of-legends-icons-by-fazie69/png/512x512/Lissandra%20Bloodstone.png',
// 		gameDescription: 'League of Legends is a popular multiplayer online battle arena (MOBA) game.',
// 		tariffs: [
// 			{
// 				id: 5,
// 				gameId: 3,
// 				name: 'Starter',
// 				description: 'Get started with League of Legends with this beginner-friendly tariff.',
// 				minSlots: 1,
// 				maxSlots: 5,
// 				monthPrice: 10,
// 				isPricePerPlayer: true,
// 				allocatedCpu: 50,
// 				allocatedDiskSpace: 15360,
// 				allocatedMemory: 4096,
// 				cpuFrequency: 3100,
// 				cpuName: 'Intel Core i3',
// 				isCpuPerSlot: false,
// 				isMemoryPerSlot: false,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 6,
// 						name: 'Africa',
// 						description: 'Africa',
// 						testIp: '192.168.0.6',
// 					},
// 				],
// 			},
// 			{
// 				id: 6,
// 				gameId: 3,
// 				name: 'Pro',
// 				description:
// 					'Take your League of Legends skills to the professional level with this tariff.',
// 				minSlots: 3,
// 				maxSlots: 15,
// 				monthPrice: 20,
// 				isPricePerPlayer: true,
// 				allocatedCpu: 100,
// 				allocatedDiskSpace: 30720,
// 				allocatedMemory: 8192,
// 				cpuFrequency: 4300,
// 				cpuName: 'Intel Core i7',
// 				isCpuPerSlot: true,
// 				isMemoryPerSlot: true,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 7,
// 						name: 'Europe',
// 						description: 'Europe',
// 						testIp: '192.168.0.7',
// 					},
// 				],
// 			},
// 		],
// 	},
// 	{
// 		gameId: 4,
// 		gameName: 'Call of Duty: Warzone',
// 		gameImageUrl:
// 			'https://steamuserimages-a.akamaihd.net/ugc/1858311009519317968/800E2011012B021FAFA15A63BEDB08B99E67BAB5/?imw=512&amp;imh=512&amp;ima=fit&amp;impolicy=Letterbox&amp;imcolor=%23000000&amp;letterbox=true',
// 		gameDescription: 'Call of Duty: Warzone is a popular free-to-play battle royale game.',
// 		tariffs: [
// 			{
// 				id: 7,
// 				gameId: 4,
// 				name: 'Standard',
// 				description:
// 					'Experience the intense action of Call of Duty: Warzone with this standard tariff.',
// 				minSlots: 2,
// 				maxSlots: 6,
// 				monthPrice: 200,
// 				isPricePerPlayer: false,
// 				allocatedCpu: 70,
// 				allocatedDiskSpace: 30720,
// 				allocatedMemory: 4096,
// 				cpuFrequency: 2900,
// 				cpuName: 'Intel Core i3',
// 				isCpuPerSlot: false,
// 				isMemoryPerSlot: false,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 8,
// 						name: 'Asia',
// 						description: 'Asis',
// 						testIp: '192.168.0.8',
// 					},
// 				],
// 			},
// 			{
// 				id: 8,
// 				gameId: 4,
// 				name: 'Premium',
// 				description:
// 					'Advanced tariff, you can play with all your friends with maximum performance. No lags. 100%.',
// 				minSlots: 2,
// 				maxSlots: 6,
// 				monthPrice: 400,
// 				isPricePerPlayer: false,
// 				allocatedCpu: 140,
// 				allocatedDiskSpace: 51200,
// 				allocatedMemory: 4096,
// 				cpuFrequency: 4800,
// 				cpuName: 'Intel Core i3',
// 				isCpuPerSlot: false,
// 				isMemoryPerSlot: false,
// 				locations: [
// 					{
// 						id: 1,
// 						name: 'North America',
// 						description: 'North America',
// 						testIp: '192.168.0.1',
// 					},
// 					{
// 						id: 8,
// 						name: 'Asia',
// 						description: 'Asia',
// 						testIp: '192.168.0.8',
// 					},
// 				],
// 			},
// 		],
// 	},
// ]

// export const tariffs: ITariff[] = [
// 	{
// 		id: 1,
// 		gameId: 1,
// 		name: 'Standard',
// 		description: 'Enjoy the standard gaming experience with this Fortnite tariff.',
// 		minSlots: 2,
// 		maxSlots: 10,
// 		monthPrice: 9.99,
// 		isPricePerPlayer: false,
// 		allocatedCpu: 4,
// 		allocatedDiskSpace: 100,
// 		allocatedMemory: 8192,
// 		cpuFrequency: 3500,
// 		cpuName: 'Intel Core i7',
// 		isCpuPerSlot: false,
// 		isMemoryPerSlot: false,
// 		locations: [
// 			{
// 				id: 1,
// 				name: 'North America',
// 				testIp: '192.168.0.1',
// 			},
// 			{
// 				id: 2,
// 				name: 'Europe',
// 				testIp: '192.168.0.2',
// 			},
// 		],
// 	},
// 	{
// 		id: 2,
// 		gameId: 1,
// 		name: 'Premium',
// 		description: 'Upgrade to the premium tariff for enhanced features and performance.',
// 		minSlots: 5,
// 		maxSlots: 20,
// 		monthPrice: 19.99,
// 		isPricePerPlayer: true,
// 		allocatedCpu: 8,
// 		allocatedDiskSpace: 200,
// 		allocatedMemory: 16384,
// 		cpuFrequency: 4000,
// 		cpuName: 'Intel Core i9',
// 		isCpuPerSlot: true,
// 		isMemoryPerSlot: true,
// 		locations: [
// 			{
// 				id: 1,
// 				name: 'North America',
// 				testIp: '192.168.0.1',
// 			},
// 			{
// 				id: 3,
// 				name: 'Asia',
// 				testIp: '192.168.0.3',
// 			},
// 		],
// 	},
// 	{
// 		id: 3,
// 		gameId: 2,
// 		name: 'Basic',
// 		description: 'Experience the basics of Minecraft with this tariff.',
// 		minSlots: 4,
// 		maxSlots: 8,
// 		monthPrice: 14.99,
// 		isPricePerPlayer: false,
// 		allocatedCpu: 6,
// 		allocatedDiskSpace: 150,
// 		allocatedMemory: 12288,
// 		cpuFrequency: 3800,
// 		cpuName: 'AMD Ryzen 5',
// 		isCpuPerSlot: false,
// 		isMemoryPerSlot: false,
// 		locations: [
// 			{
// 				id: 1,
// 				name: 'North America',
// 				testIp: '192.168.0.1',
// 			},
// 			{
// 				id: 4,
// 				name: 'South America',
// 				testIp: '192.168.0.4',
// 			},
// 		],
// 	},
// 	{
// 		id: 4,
// 		gameId: 2,
// 		name: 'Advanced',
// 		description: 'Unleash your creativity with the advanced features of Minecraft.',
// 		minSlots: 10,
// 		maxSlots: 30,
// 		monthPrice: 29.99,
// 		isPricePerPlayer: true,
// 		allocatedCpu: 12,
// 		allocatedDiskSpace: 300,
// 		allocatedMemory: 24576,
// 		cpuFrequency: 4200,
// 		cpuName: 'AMD Ryzen 7',
// 		isCpuPerSlot: true,
// 		isMemoryPerSlot: true,
// 		locations: [
// 			{
// 				id: 1,
// 				name: 'North America',
// 				testIp: '192.168.0.1',
// 			},
// 			{
// 				id: 5,
// 				name: 'Oceania',
// 				testIp: '192.168.0.5',
// 			},
// 		],
// 	},
// 	{
// 		id: 5,
// 		gameId: 3,
// 		name: 'Starter',
// 		description: 'Get started with League of Legends with this beginner-friendly tariff.',
// 		minSlots: 1,
// 		maxSlots: 5,
// 		monthPrice: 4.99,
// 		isPricePerPlayer: false,
// 		allocatedCpu: 2,
// 		allocatedDiskSpace: 50,
// 		allocatedMemory: 4096,
// 		cpuFrequency: 5400,
// 		cpuName: 'Intel Core i3',
// 		isCpuPerSlot: false,
// 		isMemoryPerSlot: false,
// 		locations: [
// 			{
// 				id: 1,
// 				name: 'North America',
// 				testIp: '192.168.0.1',
// 			},
// 			{
// 				id: 6,
// 				name: 'Africa',
// 				testIp: '192.168.0.6',
// 			},
// 		],
// 	},
// 	{
// 		id: 6,
// 		gameId: 3,
// 		name: 'Pro',
// 		description: 'Take your League of Legends skills to the professional level with this tariff.',
// 		minSlots: 3,
// 		maxSlots: 15,
// 		monthPrice: 9.99,
// 		isPricePerPlayer: true,
// 		allocatedCpu: 4,
// 		allocatedDiskSpace: 100,
// 		allocatedMemory: 8192,
// 		cpuFrequency: 3.5,
// 		cpuName: 'Intel Core i7',
// 		isCpuPerSlot: true,
// 		isMemoryPerSlot: true,
// 		locations: [
// 			{
// 				id: 1,
// 				name: 'North America',
// 				testIp: '192.168.0.1',
// 			},
// 			{
// 				id: 7,
// 				name: 'Europe',
// 				testIp: '192.168.0.7',
// 			},
// 		],
// 	},
// 	{
// 		id: 7,
// 		gameId: 4,
// 		name: 'Standard',
// 		description:
// 			'Experience the intense action of Call of Duty: Warzone with this standard tariff.',
// 		minSlots: 2,
// 		maxSlots: 6,
// 		monthPrice: 9.99,
// 		isPricePerPlayer: false,
// 		allocatedCpu: 2,
// 		allocatedDiskSpace: 50,
// 		allocatedMemory: 4096,
// 		cpuFrequency: 2.2,
// 		cpuName: 'Intel Core i3',
// 		isCpuPerSlot: false,
// 		isMemoryPerSlot: false,
// 		locations: [
// 			{
// 				id: 1,
// 				name: 'North America',
// 				testIp: '192.168.0.1',
// 			},
// 			{
// 				id: 8,
// 				name: 'Asia',
// 				testIp: '192.168.0.8',
// 			},
// 		],
// 	},
// 	{
// 		id: 8,
// 		gameId: 4,
// 		name: 'Premium',
// 		description:
// 			'Advanced tariff, you can play with all your friends with maximum performance. No lags. 100%.',
// 		minSlots: 2,
// 		maxSlots: 6,
// 		monthPrice: 9.99,
// 		isPricePerPlayer: false,
// 		allocatedCpu: 2,
// 		allocatedDiskSpace: 50,
// 		allocatedMemory: 4096,
// 		cpuFrequency: 2.2,
// 		cpuName: 'Intel Core i3',
// 		isCpuPerSlot: false,
// 		isMemoryPerSlot: false,
// 		locations: [
// 			{
// 				id: 1,
// 				name: 'North America',
// 				testIp: '192.168.0.1',
// 			},
// 			{
// 				id: 8,
// 				name: 'Asia',
// 				testIp: '192.168.0.8',
// 			},
// 		],
// 	},
// ]
